IAP 1.16 rc1

diff --git a/run/mac_ci b/run/mac_ci
--- a/run/mac_ci
+++ b/run/mac_ci
@@ -46,17 +46,35 @@ else
    ${UNITY_HOME}/Unity -batchMode -quit -projectPath ${PROJECT_PATH} -executeMethod AutoBuilder.PerformMacBuild -logFile ${AUTO_HOME}/build.log
 endif
 
+# Start the server
+echo "(4) ---------- Starting python server"
+setenv x `ps -ef | grep server.py | grep 9999 | wc -l`
+rm ${AUTO_HOME}/src/result.json
+if ($x == 0) then
+  cd ${AUTO_HOME}/src
+  python server.py 9999 &
+endif
+
 # Launch application
-echo "(4) ---------- Launching IAPDemo"
+echo "(5) ---------- Launching IAPDemo"
 echo open -a ${PROJECT_PATH}/Builds/OSX-Universal/${UNITY_VERSION}_mac.app
 echo
 open -a ${PROJECT_PATH}/Builds/OSX-Universal/${UNITY_VERSION}_mac.app
 
 # Quit application
 sleep 5
-echo "(5) ---------- Closing IAPDemo"
+echo "(6) ---------- Closing IAPDemo"
 echo osascript -e 'quit app "IAPDemo"'
 echo
 if ($3 != "") then
    osascript -e 'quit app "IAPDemo"'
+endif
+
+# Assertion
+echo "(7) ---------- Assertion"
+echo diff ${AUTO_HOME}/src/result.json ${AUTO_HOME}/src/mac_result.json
+diff ${AUTO_HOME}/src/result.json ${AUTO_HOME}/src/mac_result.json
+if ($status != 0) then
+  echo "Assertion failed"
+  exit 1
 endif
